export const CERTIFICATIONS_LIST = [
  {
    id: 1,
    name: 'Certification 1',
    issuer: 'Issuing Organization',
    date: 'Jan 2024',
    description: 'Professional certification demonstrating expertise in modern web development and best practices.',
    credential: '#',
  },
  {
    id: 2,
    name: 'Certification 2',
    issuer: 'Issuing Organization',
    date: 'Mar 2024',
    description: 'Advanced certification covering full-stack development and system architecture design patterns.',
    credential: '#',
  },
  {
    id: 3,
    name: 'Certification 3',
    issuer: 'Issuing Organization',
    date: 'May 2024',
    description: 'Specialized certification in cloud infrastructure and DevOps best practices for scalable applications.',
    credential: '#',
  },
  {
    id: 4,
    name: 'Certification 4',
    issuer: 'Issuing Organization',
    date: 'Jul 2024',
    description: 'Industry-recognized credential validating expertise in modern database design and optimization.',
    credential: '#',
  },
  {
    id: 5,
    name: 'Certification 5',
    issuer: 'Issuing Organization',
    date: 'Sep 2024',
    description: 'Professional certification demonstrating proficiency in frontend frameworks and responsive design.',
    credential: '#',
  },
  {
    id: 6,
    name: 'Certification 6',
    issuer: 'Issuing Organization',
    date: 'Nov 2024',
    description: 'Advanced certification in cybersecurity and secure coding practices for production applications.',
    credential: '#',
  },
];
