export const CERTIFICATIONS_LIST = [
  {
    id: 1,
    name: 'Canva Essentials',
    issuer: 'Canva',
    date: 'March 2024',
    description: 'Certificate of Completion of Canva Essentials',
    credential: '/canva_certificate1 image.jpg',
    image: '/canva_certificate1 image.jpg',
  },
  {
    id: 2,
    name: 'Security and Compliance',
    issuer: 'Nestle',
    date: 'May 2026',
    description: 'Certificate of Completion security and compliance induction training',
    credential: '/Security and Compliance certificate.jpeg',
    image: '/Security and Compliance certificate.jpeg',
  },
  {
    id: 3,
    name: 'Data Science Week',
    issuer: 'SQI',
    date: 'April 2025',
    description: 'Certificate of participation 3 days data science week training',
    credential: '/3- day Data analysis CERT_84.jpg',
    image: '/3- day Data analysis CERT_84.jpg',
  },
  {
    id: 4,
    name: 'Coming Soon',
    issuer: 'Coming Soon',
    date: 'Coming Soon',
    description: 'Coming Soon',
    credential: '#',
    image: '',
  },
  {
    id: 5,
    name: 'Coming Soon',
    issuer: 'Coming Soon',
    date: 'Coming Soon',
    description: 'Coming Soon',
    credential: '#',
    image: '',
  },
  {
    id: 6,
    name: 'Coming Soon',
    issuer: 'Coming Soon',
    date: 'Coming Soon',
    description: 'Coming Soon',
    credential: '#',
    image: '',
  },
];
