export const PROJECTS_LIST = [
  {
    id: 1,
    name: 'Medicdiet Clinic',
    description: 'Medicdiet clinic - a dietetic consulatation website',
    tech: ['MongoDB', 'Express', 'React', 'Node.js'],
    github: 'https://www.medicdietclinic.com/',
    live: 'https://www.medicdietclinic.com/',
    image: '/medicdiet clinic.png',
  },
  {
    id: 2,
    name: 'Note Box',
    description: 'Note box - A note keeping app',
    tech: ['JavaScript', 'Firebase'],
    github: 'https://note-box-95a03.web.app/',
    live: 'https://note-box-95a03.web.app/',
    image: '/Note keeping webapp.png',
  },
  {
    id: 3,
    name: 'QR Attendance System',
    description: 'QR based attendance system',
    tech: ['MongoDB', 'Express', 'React', 'Node.js'],
    github: 'https://qr-based-attendance-system-eight.vercel.app/',
    live: 'https://qr-based-attendance-system-eight.vercel.app/',
    image: '/QR Based attendance system.png',
  },
  {
    id: 4,
    name: 'Teleradiologist System',
    description: 'Teleradiologist manegement system',
    tech: ['MongoDB', 'Express', 'React', 'Node.js'],
    github: '#',
    live: '#',
    image: '/teleradiologist management system.png',
  },
  {
    id: 5,
    name: 'Strivex',
    description: 'a digital logbook for siwes',
    tech: ['MongoDB', 'Express', 'React', 'Node.js'],
    github: 'https://dev-caroline.github.io/Strivex/',
    live: 'https://dev-caroline.github.io/Strivex/',
    image: '/Digital logbook.png',
  },
  {
    id: 6,
    name: 'Coming Soon',
    description: 'Coming Soon',
    tech: ['Next.js', 'GraphQL', 'PostgreSQL'],
    github: '#',
    live: '#',
    image: '',
  },
];
