export const PROJECTS_LIST = [
  {
    id: 1,
    name: 'Project 1',
    description: 'A powerful full-stack web application built with modern technologies. Optimized for performance and scalability.',
    tech: ['React', 'Node.js', 'MongoDB'],
    github: '#',
    live: '#',
  },
  {
    id: 2,
    name: 'Project 2',
    description: 'Real-time collaborative tool designed for seamless team communication. Built with cutting-edge web technologies.',
    tech: ['Next.js', 'Express', 'Firebase'],
    github: '#',
    live: '#',
  },
  {
    id: 3,
    name: 'Project 3',
    description: 'E-commerce platform with advanced features. Full integration with payment systems and inventory management.',
    tech: ['React', 'TypeScript', 'PostgreSQL'],
    github: '#',
    live: '#',
  },
  {
    id: 4,
    name: 'Project 4',
    description: 'SaaS dashboard for data analytics. Provides real-time insights with interactive visualizations and reports.',
    tech: ['Next.js', 'TailwindCSS', 'MongoDB'],
    github: '#',
    live: '#',
  },
  {
    id: 5,
    name: 'Project 5',
    description: 'Mobile-first responsive web app for task management. Features include real-time synchronization and offline support.',
    tech: ['React', 'Redux', 'Firebase'],
    github: '#',
    live: '#',
  },
  {
    id: 6,
    name: 'Project 6',
    description: 'Content management system with intuitive UI. Built for content creators and organizations managing digital assets.',
    tech: ['Next.js', 'GraphQL', 'PostgreSQL'],
    github: '#',
    live: '#',
  },
];
